### 라이브러리 선언

In [1]:
# 데이터 처리 관련 라이브러리
import pandas as pd
# 수와 관련된 계산 라이브러리
import numpy as np

### 1. 데이터 불러오기

In [10]:
# 데이터 불러오기
customerData = pd.read_csv("../dataset/customerdata.csv")
# 데이터 저장하기
customerData.to_csv("./outdata.csv", index=False)

In [15]:
# 고객의 PAINPOINT..
customerData.describe()

          AVGPRICE         EMI  DEVICECOUNT  PRODUCTAGE
count   150.000000  150.000000   150.000000  150.000000
mean   3432.741108    2.053333     4.973333    1.932601
std     371.571877    0.445510     0.996279    0.807457
min    2390.083736    1.000000     3.000000    0.800000
25%    3214.543122    2.000000     4.000000    1.000000
50%    3408.300000    2.000000     5.000000    2.077000
75%    3664.767001    2.000000     6.000000    2.574525
max    4296.873743    3.000000     6.000000    3.483573

### 1. 데이터 행 조회하기

In [18]:
customerData.head(2)

   CUSTID    AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.90000    3            6    1.679181  Big-Screen-lover
1  A14219  3642.44195    2            4    2.682023      Sleeping-dog

In [ ]:
# 조건은 데이터 타입을 정확히 맞춰 줘야한다
targetEmi = "3"
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi)]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE  EMI2
0    A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover   3.0
27   F17131  3179.708359  3.0            6    1.100000        Early-bird   3.0
33   G16437  3787.328898  3.0            6    1.000000        Early-bird   3.0
36   G18402  3402.199381  3.0            6    1.000000        Early-bird   3.0
40   H16326  3988.935304  3.0            6    0.900000        Early-bird   3.0
45   I12899  3018.895637  3.0            6    0.900000        Early-bird   3.0
51   J10809  3676.135627  3.0            6    0.800000        Early-bird   3.0
52   J15083  2811.265932  3.0            6    0.900000        Early-bird   3.0
53   J16445  3041.848186  3.0            6    0.800000        Early-bird   3.0
60   L13892  3263.515145  3.0            6    1.100000        Early-bird   3.0
67   N13273  3839.694732  3.0            6    1.100000        Early-bird   3.0
95   R16364  3592.353540  3.0            6    0.900000        Early-bird   3.0
107  S17396  3895.200000  3.0            6    2.055707  Big-Screen-lover   3.0
113  T11473  4165.700000  3.0            6    1.780674  Big-Screen-lover   3.0
126  V18566  3527.701867  3.0            6    0.900000        Early-bird   3.0
130  W13404  4296.873743  3.0            6    1.100000        Early-bird   3.0
135  X13390  2947.543982  3.0            6    1.100000        Early-bird   3.0
142  Z11525  3259.018704  3.0            6    0.900000        Early-bird   3.0
146  Z13534  3662.437527  3.0            6    0.900000        Early-bird   3.0

In [40]:
# 다중 조건은 각 조건을 괄호로 묶어줘야 한다.
targetEmi = 3
targetPrice = 4000
# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ (customerData.EMI == targetEmi) &
            (customerData.AVGPRICE >= targetPrice)     ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
113  T11473  4165.700000    3            6    1.780674  Big-Screen-lover
130  W13404  4296.873743    3            6    1.100000        Early-bird

In [42]:
## 특정 컬럼에 대한 다중 값 조회 시 isin
## 해당 부정 표현 NOT IN isin 조건 앞에 ~ 를 붙여주면 된다.
targetEmiList = [1,3]

# 무이자할부가 3건 이면서 평균구매가격이 3000달러 이상인 고객을 조회해줘
resultData = customerData.loc[ ~customerData.EMI.isin(targetEmiList) ]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
5    B16849  3755.263391    2            4    2.786665      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
144  Z12772  3029.600000    2            4    2.093035  Big-Screen-lover
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[120 rows x 6 columns]

### 2. 데이터 타입 변환

In [58]:
# 데이터 타입 확인
customerData.dtypes
# EMI 컬럼 INT -> FLOAT
customerData["EMI"] =customerData.EMI.astype(float)

In [63]:
# 인덱스로도 조회가 가능하다
targetIndex = [0,1,3]
customerData.loc[ targetIndex ]

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE  EMI2
0  A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover   3.0
1  A14219  3642.441950  2.0            4    2.682023      Sleeping-dog   2.0
3  A16605  3713.211107  2.0            6    0.900000        Early-bird   2.0